
package com.odysystems.soap.ultipro.EmployeeInfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeeEmploymentInformation", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEmployeeEmploymentInformation {


    /**
     * 
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeInfo.PingResponse
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/IUesWcfService/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.EmployeeInfo.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.EmployeeInfo.Joker")
    public PingResponse ping();

    /**
     * 
     * @param employeeIdentifier
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeInfo.EmploymentInformationGetResponse
     */
    @WebMethod(operationName = "GetEmploymentInformationByEmployeeIdentifier", action = "http://www.ultipro.com/services/employeeemploymentinformation/IEmployeeEmploymentInformation/GetEmploymentInformationByEmployeeIdentifier")
    @WebResult(name = "GetEmploymentInformationByEmployeeIdentifierResult", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
    @RequestWrapper(localName = "GetEmploymentInformationByEmployeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.GetEmploymentInformationByEmployeeIdentifier")
    @ResponseWrapper(localName = "GetEmploymentInformationByEmployeeIdentifierResponse", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.GetEmploymentInformationByEmployeeIdentifierResponse")
    public EmploymentInformationGetResponse getEmploymentInformationByEmployeeIdentifier(
        @WebParam(name = "employeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
        EmployeeIdentifier employeeIdentifier);

    /**
     * 
     * @param query
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeInfo.EmploymentInformationFindResponse
     */
    @WebMethod(operationName = "FindEmploymentInformations", action = "http://www.ultipro.com/services/employeeemploymentinformation/IEmployeeEmploymentInformation/FindEmploymentInformations")
    @WebResult(name = "FindEmploymentInformationsResult", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
    @RequestWrapper(localName = "FindEmploymentInformations", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.FindEmploymentInformations")
    @ResponseWrapper(localName = "FindEmploymentInformationsResponse", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.FindEmploymentInformationsResponse")
    public EmploymentInformationFindResponse findEmploymentInformations(
        @WebParam(name = "query", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
        EmployeeQuery query);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeInfo.EmploymentInformationUpdateResponse
     */
    @WebMethod(operationName = "UpdateEmploymentInformation", action = "http://www.ultipro.com/services/employeeemploymentinformation/IEmployeeEmploymentInformation/UpdateEmploymentInformation")
    @WebResult(name = "UpdateEmploymentInformationResult", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
    @RequestWrapper(localName = "UpdateEmploymentInformation", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.UpdateEmploymentInformation")
    @ResponseWrapper(localName = "UpdateEmploymentInformationResponse", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation", className = "com.odysystems.soap.ultipro.EmployeeInfo.UpdateEmploymentInformationResponse")
    public EmploymentInformationUpdateResponse updateEmploymentInformation(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeeemploymentinformation")
        ArrayOfEmploymentInformation entities);

}
