
package com.odysystems.soap.ultipro.EmployeeInfo;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proxy_IEmployeeEmploymentInformation", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service4.ultipro.com/services/EmployeeEmploymentInformation")
@HandlerChain(file = "UltiproHandlerChain.xml")
public class ProxyIEmployeeEmploymentInformation
    extends Service
{

    private final static URL PROXYIEMPLOYEEEMPLOYMENTINFORMATION_WSDL_LOCATION;
    private final static WebServiceException PROXYIEMPLOYEEEMPLOYMENTINFORMATION_EXCEPTION;
    private final static QName PROXYIEMPLOYEEEMPLOYMENTINFORMATION_QNAME = new QName("http://tempuri.org/", "Proxy_IEmployeeEmploymentInformation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service4.ultipro.com/services/EmployeeEmploymentInformation");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROXYIEMPLOYEEEMPLOYMENTINFORMATION_WSDL_LOCATION = url;
        PROXYIEMPLOYEEEMPLOYMENTINFORMATION_EXCEPTION = e;
    }

    public ProxyIEmployeeEmploymentInformation() {
        super(__getWsdlLocation(), PROXYIEMPLOYEEEMPLOYMENTINFORMATION_QNAME);
    }

    public ProxyIEmployeeEmploymentInformation(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROXYIEMPLOYEEEMPLOYMENTINFORMATION_QNAME, features);
    }

    public ProxyIEmployeeEmploymentInformation(URL wsdlLocation) {
        super(wsdlLocation, PROXYIEMPLOYEEEMPLOYMENTINFORMATION_QNAME);
    }

    public ProxyIEmployeeEmploymentInformation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROXYIEMPLOYEEEMPLOYMENTINFORMATION_QNAME, features);
    }

    public ProxyIEmployeeEmploymentInformation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyIEmployeeEmploymentInformation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeeEmploymentInformation
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeEmploymentInformation")
    public IEmployeeEmploymentInformation getWSHttpBindingIEmployeeEmploymentInformation() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeEmploymentInformation"), IEmployeeEmploymentInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeeEmploymentInformation
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeEmploymentInformation")
    public IEmployeeEmploymentInformation getWSHttpBindingIEmployeeEmploymentInformation(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeEmploymentInformation"), IEmployeeEmploymentInformation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROXYIEMPLOYEEEMPLOYMENTINFORMATION_EXCEPTION!= null) {
            throw PROXYIEMPLOYEEEMPLOYMENTINFORMATION_EXCEPTION;
        }
        return PROXYIEMPLOYEEEMPLOYMENTINFORMATION_WSDL_LOCATION;
    }

}
