
package com.odysystems.soap.ultipro.employeeAddress;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeeAddress", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEmployeeAddress {


    /**
     * 
     * @return
     *     returns com.odysystems.soap.ultipro.employeeAddress.PingResponse
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/IUesWcfService/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.employeeAddress.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.employeeAddress.Joker")
    public PingResponse ping();

    /**
     * 
     * @param employeeIdentifier
     * @return
     *     returns com.odysystems.soap.ultipro.employeeAddress.AddressGetResponse
     */
    @WebMethod(operationName = "GetAddressByEmployeeIdentifier", action = "http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/GetAddressByEmployeeIdentifier")
    @WebResult(name = "GetAddressByEmployeeIdentifierResult", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
    @RequestWrapper(localName = "GetAddressByEmployeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.GetAddressByEmployeeIdentifier")
    @ResponseWrapper(localName = "GetAddressByEmployeeIdentifierResponse", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.GetAddressByEmployeeIdentifierResponse")
    public AddressGetResponse getAddressByEmployeeIdentifier(
        @WebParam(name = "employeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
        EmployeeIdentifier employeeIdentifier);

    /**
     * 
     * @param query
     * @return
     *     returns com.odysystems.soap.ultipro.employeeAddress.AddressFindResponse
     */
    @WebMethod(operationName = "FindAddresses", action = "http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/FindAddresses")
    @WebResult(name = "FindAddressesResult", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
    @RequestWrapper(localName = "FindAddresses", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.FindAddresses")
    @ResponseWrapper(localName = "FindAddressesResponse", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.FindAddressesResponse")
    public AddressFindResponse findAddresses(
        @WebParam(name = "query", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
        EmployeeQuery query);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.employeeAddress.AddressUpdateResponse
     */
    @WebMethod(operationName = "UpdateAddress", action = "http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/UpdateAddress")
    @WebResult(name = "UpdateAddressResult", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
    @RequestWrapper(localName = "UpdateAddress", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.UpdateAddress")
    @ResponseWrapper(localName = "UpdateAddressResponse", targetNamespace = "http://www.ultipro.com/services/employeeaddress", className = "com.odysystems.soap.ultipro.employeeAddress.UpdateAddressResponse")
    public AddressUpdateResponse updateAddress(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeeaddress")
        ArrayOfAddress entities);

}
