
package com.odysystems.soap.ultipro.employeeAddress;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proxy_IEmployeeAddress", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service4.ultipro.com/services/EmployeeAddress")
@HandlerChain(file = "UltiproHandlerChain.xml")
public class ProxyIEmployeeAddress
    extends Service
{

    private final static URL PROXYIEMPLOYEEADDRESS_WSDL_LOCATION;
    private final static WebServiceException PROXYIEMPLOYEEADDRESS_EXCEPTION;
    private final static QName PROXYIEMPLOYEEADDRESS_QNAME = new QName("http://tempuri.org/", "Proxy_IEmployeeAddress");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service4.ultipro.com/services/EmployeeAddress");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROXYIEMPLOYEEADDRESS_WSDL_LOCATION = url;
        PROXYIEMPLOYEEADDRESS_EXCEPTION = e;
    }

    public ProxyIEmployeeAddress() {
        super(__getWsdlLocation(), PROXYIEMPLOYEEADDRESS_QNAME);
    }

    public ProxyIEmployeeAddress(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROXYIEMPLOYEEADDRESS_QNAME, features);
    }

    public ProxyIEmployeeAddress(URL wsdlLocation) {
        super(wsdlLocation, PROXYIEMPLOYEEADDRESS_QNAME);
    }

    public ProxyIEmployeeAddress(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROXYIEMPLOYEEADDRESS_QNAME, features);
    }

    public ProxyIEmployeeAddress(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyIEmployeeAddress(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeeAddress
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeAddress")
    public IEmployeeAddress getWSHttpBindingIEmployeeAddress() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeAddress"), IEmployeeAddress.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeeAddress
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeAddress")
    public IEmployeeAddress getWSHttpBindingIEmployeeAddress(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeAddress"), IEmployeeAddress.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROXYIEMPLOYEEADDRESS_EXCEPTION!= null) {
            throw PROXYIEMPLOYEEADDRESS_EXCEPTION;
        }
        return PROXYIEMPLOYEEADDRESS_WSDL_LOCATION;
    }

}
