
package com.odysystems.soap.ultipro.EmployeeJob;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeeJob", targetNamespace = "http://www.ultipro.com/services/employeejob")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEmployeeJob {


    /**
     * 
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeJob.PingResponse
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/IUesWcfService/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.EmployeeJob.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.EmployeeJob.Joker")
    public PingResponse ping();

    /**
     * 
     * @param employeeIdentifier
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeJob.JobGetResponse
     */
    @WebMethod(operationName = "GetJobByEmployeeIdentifier", action = "http://www.ultipro.com/services/employeejob/IEmployeeJob/GetJobByEmployeeIdentifier")
    @WebResult(name = "GetJobByEmployeeIdentifierResult", targetNamespace = "http://www.ultipro.com/services/employeejob")
    @RequestWrapper(localName = "GetJobByEmployeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.GetJobByEmployeeIdentifier")
    @ResponseWrapper(localName = "GetJobByEmployeeIdentifierResponse", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.GetJobByEmployeeIdentifierResponse")
    public JobGetResponse getJobByEmployeeIdentifier(
        @WebParam(name = "employeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeejob")
        EmployeeIdentifier employeeIdentifier);

    /**
     * 
     * @param query
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeJob.JobFindResponse
     */
    @WebMethod(operationName = "FindJobs", action = "http://www.ultipro.com/services/employeejob/IEmployeeJob/FindJobs")
    @WebResult(name = "FindJobsResult", targetNamespace = "http://www.ultipro.com/services/employeejob")
    @RequestWrapper(localName = "FindJobs", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.FindJobs")
    @ResponseWrapper(localName = "FindJobsResponse", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.FindJobsResponse")
    public JobFindResponse findJobs(
        @WebParam(name = "query", targetNamespace = "http://www.ultipro.com/services/employeejob")
        EmployeeQuery query);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.EmployeeJob.JobUpdateResponse
     */
    @WebMethod(operationName = "UpdateJob", action = "http://www.ultipro.com/services/employeejob/IEmployeeJob/UpdateJob")
    @WebResult(name = "UpdateJobResult", targetNamespace = "http://www.ultipro.com/services/employeejob")
    @RequestWrapper(localName = "UpdateJob", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.UpdateJob")
    @ResponseWrapper(localName = "UpdateJobResponse", targetNamespace = "http://www.ultipro.com/services/employeejob", className = "com.odysystems.soap.ultipro.EmployeeJob.UpdateJobResponse")
    public JobUpdateResponse updateJob(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeejob")
        ArrayOfJob entities);

}
