
package com.odysystems.soap.ultipro.EmployeeJob;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proxy_IEmployeeJob", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service4.ultipro.com/services/EmployeeJob")
@HandlerChain(file = "UltiproHandlerChain.xml")
public class ProxyIEmployeeJob
    extends Service
{

    private final static URL PROXYIEMPLOYEEJOB_WSDL_LOCATION;
    private final static WebServiceException PROXYIEMPLOYEEJOB_EXCEPTION;
    private final static QName PROXYIEMPLOYEEJOB_QNAME = new QName("http://tempuri.org/", "Proxy_IEmployeeJob");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service4.ultipro.com/services/EmployeeJob");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROXYIEMPLOYEEJOB_WSDL_LOCATION = url;
        PROXYIEMPLOYEEJOB_EXCEPTION = e;
    }

    public ProxyIEmployeeJob() {
        super(__getWsdlLocation(), PROXYIEMPLOYEEJOB_QNAME);
    }

    public ProxyIEmployeeJob(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROXYIEMPLOYEEJOB_QNAME, features);
    }

    public ProxyIEmployeeJob(URL wsdlLocation) {
        super(wsdlLocation, PROXYIEMPLOYEEJOB_QNAME);
    }

    public ProxyIEmployeeJob(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROXYIEMPLOYEEJOB_QNAME, features);
    }

    public ProxyIEmployeeJob(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyIEmployeeJob(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeeJob
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeJob")
    public IEmployeeJob getWSHttpBindingIEmployeeJob() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeJob"), IEmployeeJob.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeeJob
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeJob")
    public IEmployeeJob getWSHttpBindingIEmployeeJob(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeJob"), IEmployeeJob.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROXYIEMPLOYEEJOB_EXCEPTION!= null) {
            throw PROXYIEMPLOYEEJOB_EXCEPTION;
        }
        return PROXYIEMPLOYEEJOB_WSDL_LOCATION;
    }

}
