//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 04:11:25 PM EST 
//


package com.odysystems.model.soap.costpoint;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cb_S_DED_MTHD_CD.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cb_S_DED_MTHD_CD">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="6"/>
 *     &lt;enumeration value="ADDGRS"/>
 *     &lt;enumeration value="FIXAMT"/>
 *     &lt;enumeration value="GHRSPD"/>
 *     &lt;enumeration value="GRSHRF"/>
 *     &lt;enumeration value="GRSHRP"/>
 *     &lt;enumeration value="NO DED"/>
 *     &lt;enumeration value="PCTANN"/>
 *     &lt;enumeration value="PCTCOD"/>
 *     &lt;enumeration value="PCTDPI"/>
 *     &lt;enumeration value="PCTGRS"/>
 *     &lt;enumeration value="PCTNET"/>
 *     &lt;enumeration value="PCTREG"/>
 *     &lt;enumeration value="REGHRF"/>
 *     &lt;enumeration value="REGHRP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cb_S_DED_MTHD_CD")
@XmlEnum
public enum CbSDEDMTHDCD {

    ADDGRS("ADDGRS"),
    FIXAMT("FIXAMT"),
    GHRSPD("GHRSPD"),
    GRSHRF("GRSHRF"),
    GRSHRP("GRSHRP"),
    @XmlEnumValue("NO DED")
    NO_DED("NO DED"),
    PCTANN("PCTANN"),
    PCTCOD("PCTCOD"),
    PCTDPI("PCTDPI"),
    PCTGRS("PCTGRS"),
    PCTNET("PCTNET"),
    PCTREG("PCTREG"),
    REGHRF("REGHRF"),
    REGHRP("REGHRP");
    private final String value;

    CbSDEDMTHDCD(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CbSDEDMTHDCD fromValue(String v) {
        for (CbSDEDMTHDCD c: CbSDEDMTHDCD.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
