//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 04:11:25 PM EST 
//


package com.odysystems.model.soap.costpoint;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cb_S_EMPL_STATUS_CD.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cb_S_EMPL_STATUS_CD">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="3"/>
 *     &lt;enumeration value="ACT"/>
 *     &lt;enumeration value="FML"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="IAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cb_S_EMPL_STATUS_CD")
@XmlEnum
public enum CbSEMPLSTATUSCD {

    ACT,
    FML,
    IN,
    IAL;

    public String value() {
        return name();
    }

    public static CbSEMPLSTATUSCD fromValue(String v) {
        return valueOf(v);
    }

}
