//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.20 at 04:11:25 PM EST 
//


package com.odysystems.model.soap.costpoint;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cb_TIME_ENTRY_TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cb_TIME_ENTRY_TYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="40"/>
 *     &lt;enumeration value="PUNCHED"/>
 *     &lt;enumeration value="EXCEPTION"/>
 *     &lt;enumeration value="ELAPSED"/>
 *     &lt;enumeration value="NONE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cb_TIME_ENTRY_TYPE")
@XmlEnum
public enum CbTIMEENTRYTYPE {

    PUNCHED,
    EXCEPTION,
    ELAPSED,
    NONE;

    public String value() {
        return name();
    }

    public static CbTIMEENTRYTYPE fromValue(String v) {
        return valueOf(v);
    }

}
