/**
 * Text_fileDocument.java
 *
 * This file was generated by MapForce 2015sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.odysseyconsult.breerabbit.translator.Text_file;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class Text_fileDocument extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(false);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(1 == 1);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("Field14"));
		header.add(new ColumnSpecification("Field13"));
		header.add(new ColumnSpecification("Field12"));
		header.add(new ColumnSpecification("Field1"));
		header.add(new ColumnSpecification("Field5"));
	}
	public Text_fileDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
        super( tableType,lineend);
    }
}



