/**
 * BreerRabbitConsole.java
 *
 * This file was generated by MapForce 2015sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.odysseyconsult.breerabbit.translator;

import com.altova.types.*;


public class BreerRabbitConsole {

	public static void main(String[] args) {
		System.out.println("BreerRabbit Application");

		java.util.Hashtable	mapArguments = new java.util.Hashtable();
		if( args.length <= 1 )	{
			System.out.println();
			System.out.println( "WARNING: No parameters given!");
			System.out.println( "SYNTAX: java com.mapforce.BreerRabbitConsole /Date ... ");
			System.out.println( "SYNTAX: ant -Dcmdline=\"/Date ... \"");
			System.out.println( "Note: If you want to use spaces as values write them in-between double quotes." );
			System.out.println();
		}
		else
		{
			for( int i = 0; i < args.length; i++ )
			{
				String sName = args[ i ];
				if( sName.substring( 0, 1 ).equals( "/" )  &&  ( i + 1 ) < args.length )
					mapArguments.put( sName.substring( 1, sName.length() ), args[ ++i ] );
			}
		}

		try { // Mapping
			TraceTargetConsole ttc = new TraceTargetConsole();


			MappingMapToUTM_Input MappingMapToUTM_InputObject = new MappingMapToUTM_Input();




			MappingMapToUTM_InputObject.registerTraceTarget(ttc);
	

			// run mapping
			//
			// you have different options to provide mapping input and output:
			//
			// files using file names (available for XML, text, and Excel):
			//   com.altova.io.FileInput(String filename)
			//   com.altova.io.FileOutput(String filename)
			//
			// streams (available for XML, text, and Excel):
			//   com.altova.io.StreamInput(java.io.InputStream stream)
			//   com.altova.io.StreamOutput(java.io.OutputStream stream)
			//
			// strings (available for XML and text):
			//   com.altova.io.StringInput(String xmlcontent)
			//   com.altova.io.StringOutput()	(call getContent() after run() to get StringBuffer with content)
			//
			// Java IO reader/writer (available for XML and text):
			//   com.altova.io.ReaderInput(java.io.Reader reader)
			//   com.altova.io.WriterOutput(java.io.Writer writer)
			//
			// DOM documents (for XML only):
			//   com.altova.io.DocumentInput(org.w3c.dom.Document document)
			//   com.altova.io.DocumentOutput(org.w3c.dom.Document document)
			// 
			// By default, run will close all inputs and outputs. If you do not want this,
			// call the following function:
			// MappingMapToUTM_InputObject.setCloseObjectsAfterRun(false);

			{
				com.altova.io.Input Deltek_GCS_Payroll_Output2Source = com.altova.io.StreamInput.createInput("09 23 16 Deltek_Round1 Processed.CSV");
				com.altova.io.Output UTM_InputTarget = new com.altova.io.FileOutput("UTM_DATE_Import");

				MappingMapToUTM_InputObject.run(
						Deltek_GCS_Payroll_Output2Source,
						UTM_InputTarget);
			}



			System.out.println("Finished");
		} 
		catch (com.altova.UserException ue) 
		{
			System.out.print("USER EXCEPTION:");
			System.out.println( ue.getMessage() );
			System.exit(1);
		}
		catch (com.altova.AltovaException e)
		{
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			if (e.getInnerException() != null)
			{
				System.out.print("Inner exception: ");
				System.out.println(e.getInnerException().getMessage());
				if (e.getInnerException().getCause() != null)
				{
					System.out.print("Cause: ");
					System.out.println(e.getInnerException().getCause().getMessage());
				}
			}
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}
		
		catch (Exception e) {
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}

		try { // Mapping
			TraceTargetConsole ttc = new TraceTargetConsole();


			MappingMapToUTM_Input2 MappingMapToUTM_Input2Object = new MappingMapToUTM_Input2();




			MappingMapToUTM_Input2Object.registerTraceTarget(ttc);
	
			if(!mapArguments.containsKey("Date"))
			{
				System.out.println("Missing argument Date");
				System.exit(1);
			}

			// run mapping
			//
			// you have different options to provide mapping input and output:
			//
			// files using file names (available for XML, text, and Excel):
			//   com.altova.io.FileInput(String filename)
			//   com.altova.io.FileOutput(String filename)
			//
			// streams (available for XML, text, and Excel):
			//   com.altova.io.StreamInput(java.io.InputStream stream)
			//   com.altova.io.StreamOutput(java.io.OutputStream stream)
			//
			// strings (available for XML and text):
			//   com.altova.io.StringInput(String xmlcontent)
			//   com.altova.io.StringOutput()	(call getContent() after run() to get StringBuffer with content)
			//
			// Java IO reader/writer (available for XML and text):
			//   com.altova.io.ReaderInput(java.io.Reader reader)
			//   com.altova.io.WriterOutput(java.io.Writer writer)
			//
			// DOM documents (for XML only):
			//   com.altova.io.DocumentInput(org.w3c.dom.Document document)
			//   com.altova.io.DocumentOutput(org.w3c.dom.Document document)
			// 
			// By default, run will close all inputs and outputs. If you do not want this,
			// call the following function:
			// MappingMapToUTM_Input2Object.setCloseObjectsAfterRun(false);

			{
				com.altova.io.Input PayrollIISource = com.altova.io.StreamInput.createInput("10 07 16 Deltek.CSV");
				com.altova.io.Output UTM_Input2Target = new com.altova.io.FileOutput("UTM_DATE_Import_II.csv");

				MappingMapToUTM_Input2Object.run(
						PayrollIISource,
						com.altova.CoreTypes.castToString((String)mapArguments.get("Date")),
						UTM_Input2Target);
			}



			System.out.println("Finished");
		} 
		catch (com.altova.UserException ue) 
		{
			System.out.print("USER EXCEPTION:");
			System.out.println( ue.getMessage() );
			System.exit(1);
		}
		catch (com.altova.AltovaException e)
		{
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			if (e.getInnerException() != null)
			{
				System.out.print("Inner exception: ");
				System.out.println(e.getInnerException().getMessage());
				if (e.getInnerException().getCause() != null)
				{
					System.out.print("Cause: ");
					System.out.println(e.getInnerException().getCause().getMessage());
				}
			}
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}
		
		catch (Exception e) {
			System.out.print("ERROR: ");
			System.out.println( e.getMessage() );
			System.out.println("\nStack Trace: ");
			e.printStackTrace();
			System.exit(1);
		}

	}
}


class TraceTargetConsole implements com.altova.TraceTarget {
	public void writeTrace(String info) {
		System.out.println(info);
	}
}
