/**
 * MappingMapToUTM_Input.java
 *
 * This file was generated by MapForce 2015sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.odysseyconsult.breerabbit.translator;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import com.altova.text.tablelike.*;
import com.altova.text.*;
import com.altova.text.edi.*;
import java.util.*;

public class MappingMapToUTM_Input extends com.altova.TraceProvider 
{
	private boolean runDoesCloseAll = true;
	public void setCloseObjectsAfterRun(boolean c) {runDoesCloseAll = c;}
	public boolean getCloseObjectsAfterRun() {return runDoesCloseAll;}

	
	static class main implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_Deltek_GCS_Payroll_Output;
	
		public main(com.altova.mapforce.IMFNode var1_instance_Deltek_GCS_Payroll_Output)
		{
			this.var1_instance_Deltek_GCS_Payroll_Output = var1_instance_Deltek_GCS_Payroll_Output;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 2;
			Object current;
			main closure;
			IEnumerator var2_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var3_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var4_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var5_filter_elements_nodename;
			public Enumerator(main closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 2:	if (moveNext_2()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
					case 4:	if (moveNext_4()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 3;				
				var2_filter_elements_nodename = (com.altova.functions.Core.filterElements("Rows", closure.var1_instance_Deltek_GCS_Payroll_Output)).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 3;				
				if (!var2_filter_elements_nodename.moveNext()) {state = 4; return false; }
				var3_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Name", ((com.altova.mapforce.IMFNode)(var2_filter_elements_nodename.current()))));
				var4_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Reg Hours", ((com.altova.mapforce.IMFNode)(var2_filter_elements_nodename.current()))));
				var5_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("FILE #", ((com.altova.mapforce.IMFNode)(var2_filter_elements_nodename.current()))));
				current = com.altova.functions.Core.createElement("Rows", (new seq1_join(var3_filter_elements_nodename, var4_filter_elements_nodename, ((com.altova.mapforce.IMFNode)(var2_filter_elements_nodename.current())), var5_filter_elements_nodename)));
				pos++;
				return true;
			}
			private boolean moveNext_4() throws Exception {
				state = 0;				
				var2_filter_elements_nodename.close(); var2_filter_elements_nodename = null;
				return false;
			}

			
			public void close()
			{
				try
				{
				var2_filter_elements_nodename.close(); var2_filter_elements_nodename = null;
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq1_join implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_nodename;
		com.altova.mapforce.IEnumerable var2_filter_elements_nodename;
		com.altova.mapforce.IMFNode var3_current;
		com.altova.mapforce.IEnumerable var4_filter_elements_nodename;
	
		public seq1_join(com.altova.mapforce.IEnumerable var1_filter_elements_nodename, com.altova.mapforce.IEnumerable var2_filter_elements_nodename, com.altova.mapforce.IMFNode var3_current, com.altova.mapforce.IEnumerable var4_filter_elements_nodename)
		{
			this.var1_filter_elements_nodename = var1_filter_elements_nodename;
			this.var2_filter_elements_nodename = var2_filter_elements_nodename;
			this.var3_current = var3_current;
			this.var4_filter_elements_nodename = var4_filter_elements_nodename;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq1_join closure;
			public Enumerator(seq1_join closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 4:	if (moveNext_4()) return true; break;
					case 7:	if (moveNext_7()) return true; break;
					case 10:	if (moveNext_10()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 4;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_nodename))) {state = 4; return false; }
				current = com.altova.functions.Core.createElement("Field14", com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_nodename))));
				pos++;
				return true;
			}
			private boolean moveNext_4() throws Exception {
				state = 7;				
				if (!((Boolean)com.altova.functions.Core.first((new seq2_if_exists(closure.var2_filter_elements_nodename, closure.var3_current))))) {state = 7; return false; }
				current = com.altova.functions.Core.createElement("Field13", (new seq3_if_exists(closure.var2_filter_elements_nodename, closure.var3_current)));
				pos++;
				return true;
			}
			private boolean moveNext_7() throws Exception {
				state = 10;				
				if (!((Boolean)com.altova.functions.Core.first((new seq4_if_exists(closure.var2_filter_elements_nodename, closure.var3_current))))) {state = 10; return false; }
				current = com.altova.functions.Core.createElement("Field12", (new seq5_if_exists(closure.var2_filter_elements_nodename, closure.var3_current)));
				pos++;
				return true;
			}
			private boolean moveNext_10() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var4_filter_elements_nodename))) {state = 0; return false; }
				current = com.altova.functions.Core.createElement("Field1", com.altova.functions.Core.box(com.altova.functions.Core.concat(com.altova.functions.Core.concat("000", com.altova.functions.Core.concat("000", com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var4_filter_elements_nodename)))), "-5ZPKG")));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq2_if_exists implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_nodename;
		com.altova.mapforce.IMFNode var2_current;
	
		public seq2_if_exists(com.altova.mapforce.IEnumerable var1_filter_elements_nodename, com.altova.mapforce.IMFNode var2_current)
		{
			this.var1_filter_elements_nodename = var1_filter_elements_nodename;
			this.var2_current = var2_current;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq2_if_exists closure;
			com.altova.mapforce.IEnumerable var3_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var4_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var5_filter_elements_nodename;
			public Enumerator(seq2_if_exists closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 5:	if (moveNext_5()) return true; break;
					case 8:	if (moveNext_8()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_nodename))) {state = 2; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				var3_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("O_T Hours", closure.var2_current));
				if (!(com.altova.functions.Core.exists(var3_filter_elements_nodename))) {state = 5; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				var4_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Paid Time Off Hours 3", closure.var2_current));
				if (!(com.altova.functions.Core.exists(var4_filter_elements_nodename))) {state = 8; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_8() throws Exception {
				state = 0;				
				var5_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Holiday Hours 4", closure.var2_current));
				current = com.altova.functions.Core.exists(var5_filter_elements_nodename);
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq3_if_exists implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_nodename;
		com.altova.mapforce.IMFNode var2_current;
	
		public seq3_if_exists(com.altova.mapforce.IEnumerable var1_filter_elements_nodename, com.altova.mapforce.IMFNode var2_current)
		{
			this.var1_filter_elements_nodename = var1_filter_elements_nodename;
			this.var2_current = var2_current;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq3_if_exists closure;
			public Enumerator(seq3_if_exists closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 5:	if (moveNext_5()) return true; break;
					case 8:	if (moveNext_8()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_nodename))) {state = 2; return false; }
				current = "REG";
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements("O_T Hours", closure.var2_current)))) {state = 5; return false; }
				current = "OT";
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements("Paid Time Off Hours 3", closure.var2_current)))) {state = 8; return false; }
				current = "PTO";
				pos++;
				return true;
			}
			private boolean moveNext_8() throws Exception {
				state = 0;				
				current = "HOL";
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq4_if_exists implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_nodename;
		com.altova.mapforce.IMFNode var2_current;
	
		public seq4_if_exists(com.altova.mapforce.IEnumerable var1_filter_elements_nodename, com.altova.mapforce.IMFNode var2_current)
		{
			this.var1_filter_elements_nodename = var1_filter_elements_nodename;
			this.var2_current = var2_current;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq4_if_exists closure;
			com.altova.mapforce.IEnumerable var3_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var4_filter_elements_nodename;
			com.altova.mapforce.IEnumerable var5_filter_elements_nodename;
			public Enumerator(seq4_if_exists closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 5:	if (moveNext_5()) return true; break;
					case 8:	if (moveNext_8()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_nodename))) {state = 2; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				var3_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("O_T Hours", closure.var2_current));
				if (!(com.altova.functions.Core.exists(var3_filter_elements_nodename))) {state = 5; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				var4_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Paid Time Off Hours 3", closure.var2_current));
				if (!(com.altova.functions.Core.exists(var4_filter_elements_nodename))) {state = 8; return false; }
				current = com.altova.CoreTypes.parseBoolean("true");
				pos++;
				return true;
			}
			private boolean moveNext_8() throws Exception {
				state = 0;				
				var5_filter_elements_nodename = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements("Holiday Hours 4", closure.var2_current));
				current = com.altova.functions.Core.exists(var5_filter_elements_nodename);
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq5_if_exists implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_nodename;
		com.altova.mapforce.IMFNode var2_current;
	
		public seq5_if_exists(com.altova.mapforce.IEnumerable var1_filter_elements_nodename, com.altova.mapforce.IMFNode var2_current)
		{
			this.var1_filter_elements_nodename = var1_filter_elements_nodename;
			this.var2_current = var2_current;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq5_if_exists closure;
			public Enumerator(seq5_if_exists closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 5:	if (moveNext_5()) return true; break;
					case 8:	if (moveNext_8()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_nodename))) {state = 2; return false; }
				current = com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_nodename));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements("O_T Hours", closure.var2_current)))) {state = 5; return false; }
				current = com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements("O_T Hours", closure.var2_current)));
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements("Paid Time Off Hours 3", closure.var2_current)))) {state = 8; return false; }
				current = com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements("Paid Time Off Hours 3", closure.var2_current)));
				pos++;
				return true;
			}
			private boolean moveNext_8() throws Exception {
				state = 0;				
				current = com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements("Holiday Hours 4", closure.var2_current)));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class Outer implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_Deltek_GCS_Payroll_Output;
	
		public Outer(com.altova.mapforce.IMFNode var1_instance_Deltek_GCS_Payroll_Output)
		{
			this.var1_instance_Deltek_GCS_Payroll_Output = var1_instance_Deltek_GCS_Payroll_Output;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			Outer closure;
			IEnumerator var2_map;
			public Enumerator(Outer closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_map = ((new main(closure.var1_instance_Deltek_GCS_Payroll_Output))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_map.moveNext()) {state = 3; return false; }
				current = var2_map.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				var2_map.close(); var2_map = null;
				return false;
			}

			
			public void close()
			{
				try
				{
				var2_map.close(); var2_map = null;
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}



	// instances
	protected com.altova.text.tablelike.Table varDeltek_GCS_Payroll_Output2Instance;

	public void run(String Deltek_GCS_Payroll_Output2SourceFilename, String UTM_InputTargetFilename) throws Exception {
		// open source streams
		writeTrace("Loading " + Deltek_GCS_Payroll_Output2SourceFilename + "...\n");
		com.altova.io.FileInput Deltek_GCS_Payroll_Output2Source = new com.altova.io.FileInput(Deltek_GCS_Payroll_Output2SourceFilename);
		// open target stream
		com.altova.io.FileOutput UTM_InputTarget = new com.altova.io.FileOutput(UTM_InputTargetFilename);

		// run
		run(Deltek_GCS_Payroll_Output2Source, UTM_InputTarget);

		// close source streams
		Deltek_GCS_Payroll_Output2Source.close();
		// close target stream
		writeTrace("Saving " + UTM_InputTargetFilename + "...\n");
		UTM_InputTarget.close();
	}


	// main entry point

	public void run(com.altova.io.Input Deltek_GCS_Payroll_Output2Source, com.altova.io.Output UTM_InputTarget) throws Exception {
		// Open the source(s)
		writeTrace("Parsing Text...\n");
		com.altova.text.tablelike.csv.Table Deltek_GCS_Payroll_Output2InstanceObject = new com.altova.text.tablelike.csv.Table(com.odysseyconsult.breerabbit.translator.Deltek_GCS_Payroll_Output.Deltek_GCS_Payroll_Output_TypeInfo.binder.getTypes()[com.odysseyconsult.breerabbit.translator.Deltek_GCS_Payroll_Output.Deltek_GCS_Payroll_Output_TypeInfo._altova_ti_altova_RowsType],0);
		varDeltek_GCS_Payroll_Output2Instance = Deltek_GCS_Payroll_Output2InstanceObject;
		com.altova.text.tablelike.Table Deltek_GCS_Payroll_Output2SourceObject = varDeltek_GCS_Payroll_Output2Instance;
			Deltek_GCS_Payroll_Output2InstanceObject.getFormat().setAssumeFirstRowAsHeaders( true );
			Deltek_GCS_Payroll_Output2InstanceObject.getFormat().setFieldDelimiter( ',' );
			Deltek_GCS_Payroll_Output2InstanceObject.getFormat().setRemoveEmpty( true );
			Deltek_GCS_Payroll_Output2InstanceObject.getFormat().setQuoteCharacter( '\"' );
		varDeltek_GCS_Payroll_Output2Instance.setEncoding( "UTF-8", false, false );
		varDeltek_GCS_Payroll_Output2Instance.parse(Deltek_GCS_Payroll_Output2Source);
		if (runDoesCloseAll)
			Deltek_GCS_Payroll_Output2Source.close();

		// Create the target
		com.odysseyconsult.breerabbit.translator.Text_file.Text_fileDocument UTM_InputTargetDoc = new com.odysseyconsult.breerabbit.translator.Text_file.Text_fileDocument(com.odysseyconsult.breerabbit.translator.Text_file.Text_file_TypeInfo.binder.getTypes()[com.odysseyconsult.breerabbit.translator.Text_file.Text_file_TypeInfo._altova_ti_altova_RowsType],0);
		com.altova.text.tablelike.Table UTM_InputTargetObject = UTM_InputTargetDoc;
			UTM_InputTargetDoc.getFormat().setAssumeFirstRowAsHeaders( false );
			UTM_InputTargetDoc.getFormat().setFieldDelimiter( ',' );
			UTM_InputTargetDoc.getFormat().setRemoveEmpty( true );
			UTM_InputTargetDoc.getFormat().setQuoteCharacter( '\0' );

		// Execute mapping

		main mapping = new main(new com.altova.text.TableAsMFNodeAdapter(varDeltek_GCS_Payroll_Output2Instance, Deltek_GCS_Payroll_Output2Source.getFilename()));

		com.altova.text.MFTextWriter.write(mapping, UTM_InputTargetObject);
		// Close the target
		UTM_InputTargetDoc.setEncoding( "UTF-8", false, false );
		UTM_InputTargetDoc.save(UTM_InputTarget);

		
		if (runDoesCloseAll)
		{
			Deltek_GCS_Payroll_Output2Source.close();
			UTM_InputTarget.close();
		}
	}



}
