
package com.odysystems.soap.ultipro.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.stereotype.Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebService(name = "ILoginService", targetNamespace = "http://www.ultipro.com/services/loginservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILoginService {


    /**
     * 
     * @param password
     * @param clientAccessKey
     * @param userName
     * @param parameters
     * @param userAccessKey
     * @return
     *     returns com.odysystems.soap.ultipro.login.TokenResponse
     */
    @WebMethod(operationName = "Authenticate", action = "http://www.ultipro.com/services/loginservice/ILoginService/Authenticate")
    @WebResult(name = "TokenResponse", targetNamespace = "http://www.ultipro.com/contracts", partName = "parameters")
    public TokenResponse authenticate(
        @WebParam(name = "TokenRequest", targetNamespace = "http://www.ultipro.com/contracts", partName = "parameters")
        TokenRequest parameters,
        @WebParam(name = "ClientAccessKey", targetNamespace = "http://www.ultipro.com/services/loginservice", header = true, partName = "ClientAccessKey")
        String clientAccessKey,
        @WebParam(name = "Password", targetNamespace = "http://www.ultipro.com/services/loginservice", header = true, partName = "Password")
        String password,
        @WebParam(name = "UserAccessKey", targetNamespace = "http://www.ultipro.com/services/loginservice", header = true, partName = "UserAccessKey")
        String userAccessKey,
        @WebParam(name = "UserName", targetNamespace = "http://www.ultipro.com/services/loginservice", header = true, partName = "UserName")
        String userName);

}
