
package com.odysystems.soap.ultipro.SSOuser;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeeSsoUser", targetNamespace = "http://www.ultipro.com/services/employeessouser")
@XmlSeeAlso({
    ObjectFactory.class
})
@HandlerChain(file = "UltiproHandlerChain.xml")
public interface IEmployeeSsoUser {


    /**
     * 
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.PingResponse
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/IUesWcfService/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.SSOuser.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.SSOuser.Joker")
    public PingResponse ping();

    /**
     * 
     * @param employeeIdentifier
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserGetResponse
     */
    @WebMethod(operationName = "GetSsoUserByEmployeeIdentifier", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/GetSsoUserByEmployeeIdentifier")
    @WebResult(name = "GetSsoUserByEmployeeIdentifierResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "GetSsoUserByEmployeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.GetSsoUserByEmployeeIdentifier")
    @ResponseWrapper(localName = "GetSsoUserByEmployeeIdentifierResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.GetSsoUserByEmployeeIdentifierResponse")
    public SsoUserGetResponse getSsoUserByEmployeeIdentifier(
        @WebParam(name = "employeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeessouser")
        EmployeeIdentifier employeeIdentifier);

    /**
     * 
     * @param clientUserName
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserGetResponse
     */
    @WebMethod(operationName = "GetSsoUserByClientUserName", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/GetSsoUserByClientUserName")
    @WebResult(name = "GetSsoUserByClientUserNameResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "GetSsoUserByClientUserName", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.GetSsoUserByClientUserName")
    @ResponseWrapper(localName = "GetSsoUserByClientUserNameResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.GetSsoUserByClientUserNameResponse")
    public SsoUserGetResponse getSsoUserByClientUserName(
        @WebParam(name = "clientUserName", targetNamespace = "http://www.ultipro.com/services/employeessouser")
        String clientUserName,
		@WebParam(name = "ClientAccessKey", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey", header = true, partName = "ClientAccessKey") String clientAccessKey,
		@WebParam(name = "UltiProToken", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken", header = true, partName = "UltiProToken") String UltiProToken

        
    		);

    /**
     * 
     * @param query
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserFindResponse
     */
    @WebMethod(operationName = "FindSsoUsers", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/FindSsoUsers")
    @WebResult(name = "FindSsoUsersResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "FindSsoUsers", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.FindSsoUsers")
    @ResponseWrapper(localName = "FindSsoUsersResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.FindSsoUsersResponse")
    public SsoUserFindResponse findSsoUsers(
			@WebParam(name = "query", targetNamespace = "http://www.ultipro.com/services/employeessouser") EmployeeQuery query,
			@WebParam(name = "ClientAccessKey", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey", header = true, partName = "ClientAccessKey") String clientAccessKey,
			@WebParam(name = "UltiProToken", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken", header = true, partName = "UltiProToken") String UltiProToken

	);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserCreateResponse
     */
    @WebMethod(operationName = "CreateSsoUser", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/CreateSsoUser")
    @WebResult(name = "CreateSsoUserResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "CreateSsoUser", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.CreateSsoUser")
    @ResponseWrapper(localName = "CreateSsoUserResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.CreateSsoUserResponse")
    public SsoUserCreateResponse createSsoUser(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeessouser")
        ArrayOfSsoUser entities,
		@WebParam(name = "ClientAccessKey", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey", header = true, partName = "ClientAccessKey") String clientAccessKey,
		@WebParam(name = "UltiProToken", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken", header = true, partName = "UltiProToken") String UltiProToken
        
    		);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserUpdateResponse
     */
    @WebMethod(operationName = "UpdateSsoUser", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/UpdateSsoUser")
    @WebResult(name = "UpdateSsoUserResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "UpdateSsoUser", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.UpdateSsoUser")
    @ResponseWrapper(localName = "UpdateSsoUserResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.UpdateSsoUserResponse")
    public SsoUserUpdateResponse updateSsoUser(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeessouser")
        ArrayOfSsoUser entities);

    /**
     * 
     * @param entities
     * @return
     *     returns com.odysystems.soap.ultipro.SSOuser.SsoUserDeleteResponse
     */
    @WebMethod(operationName = "DeleteSsoUser", action = "http://www.ultipro.com/services/employeessouser/IEmployeeSsoUser/DeleteSsoUser")
    @WebResult(name = "DeleteSsoUserResult", targetNamespace = "http://www.ultipro.com/services/employeessouser")
    @RequestWrapper(localName = "DeleteSsoUser", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.DeleteSsoUser")
    @ResponseWrapper(localName = "DeleteSsoUserResponse", targetNamespace = "http://www.ultipro.com/services/employeessouser", className = "com.odysystems.soap.ultipro.SSOuser.DeleteSsoUserResponse")
    public SsoUserDeleteResponse deleteSsoUser(
        @WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeessouser")
        ArrayOfSsoUser entities);

}
