
package com.odysystems.soap.ultipro.SSOuser;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proxy_IEmployeeSsoUser", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service4.ultipro.com/services/EmployeeSsoUser")
@HandlerChain(file = "UltiproHandlerChain.xml")
public class ProxyIEmployeeSsoUser
    extends Service
{

    private final static URL PROXYIEMPLOYEESSOUSER_WSDL_LOCATION;
    private final static WebServiceException PROXYIEMPLOYEESSOUSER_EXCEPTION;
    private final static QName PROXYIEMPLOYEESSOUSER_QNAME = new QName("http://tempuri.org/", "Proxy_IEmployeeSsoUser");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service4.ultipro.com/services/EmployeeSsoUser");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROXYIEMPLOYEESSOUSER_WSDL_LOCATION = url;
        PROXYIEMPLOYEESSOUSER_EXCEPTION = e;
    }

    public ProxyIEmployeeSsoUser() {
        super(__getWsdlLocation(), PROXYIEMPLOYEESSOUSER_QNAME);
    }

    public ProxyIEmployeeSsoUser(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROXYIEMPLOYEESSOUSER_QNAME, features);
    }

    public ProxyIEmployeeSsoUser(URL wsdlLocation) {
        super(wsdlLocation, PROXYIEMPLOYEESSOUSER_QNAME);
    }

    public ProxyIEmployeeSsoUser(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROXYIEMPLOYEESSOUSER_QNAME, features);
    }

    public ProxyIEmployeeSsoUser(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyIEmployeeSsoUser(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeeSsoUser
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeSsoUser")
    public IEmployeeSsoUser getWSHttpBindingIEmployeeSsoUser() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeSsoUser"), IEmployeeSsoUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeeSsoUser
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeeSsoUser")
    public IEmployeeSsoUser getWSHttpBindingIEmployeeSsoUser(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeeSsoUser"), IEmployeeSsoUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROXYIEMPLOYEESSOUSER_EXCEPTION!= null) {
            throw PROXYIEMPLOYEESSOUSER_EXCEPTION;
        }
        return PROXYIEMPLOYEESSOUSER_WSDL_LOCATION;
    }

}
