/**
 * Deltek_GCS_Payroll_OutputDocument.java
 *
 * This file was generated by MapForce 2015sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.odysseyconsult.breerabbit.translator.Deltek_GCS_Payroll_Output;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class Deltek_GCS_Payroll_OutputDocument extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(true);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("CO CODE"));
		header.add(new ColumnSpecification("BATCH ID"));
		header.add(new ColumnSpecification("FILE #"));
		header.add(new ColumnSpecification("BATCH DESCRIPTION"));
		header.add(new ColumnSpecification("Name"));
		header.add(new ColumnSpecification("Pay #"));
		header.add(new ColumnSpecification("Tax Frequency"));
		header.add(new ColumnSpecification("Shift"));
		header.add(new ColumnSpecification("Special Action"));
		header.add(new ColumnSpecification("Reg Hours"));
		header.add(new ColumnSpecification("O/T Hours"));
		header.add(new ColumnSpecification("Paid Time Off Hours 3"));
		header.add(new ColumnSpecification("Holiday Hours 4"));
		header.add(new ColumnSpecification("Reg Earnings"));
		header.add(new ColumnSpecification("O/T Earnings"));
	}
	public Deltek_GCS_Payroll_OutputDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
        super( tableType,lineend);
    }
}



