/**
 * Name10_07_16_DeltekDocument.java
 *
 * This file was generated by MapForce 2015sp2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.odysseyconsult.breerabbit.translator.Name10_07_16_Deltek;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class Name10_07_16_DeltekDocument extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(true);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("CO CODE"));
		header.add(new ColumnSpecification("BATCH ID"));
		header.add(new ColumnSpecification("FILE #"));
		header.add(new ColumnSpecification("PAY #"));
		header.add(new ColumnSpecification("SHIFT"));
		header.add(new ColumnSpecification("SPECIAL ACTION"));
		header.add(new ColumnSpecification("REG HOURS"));
		header.add(new ColumnSpecification("O/T HOURS"));
		header.add(new ColumnSpecification("HOURS 3 CODE"));
		header.add(new ColumnSpecification("HOURS 3 AMOUNT"));
		header.add(new ColumnSpecification("HOURS 4 CODE"));
		header.add(new ColumnSpecification("HOURS 4 AMOUNT"));
		header.add(new ColumnSpecification("REG EARNINGS"));
		header.add(new ColumnSpecification("O/T EARNINGS"));
		header.add(new ColumnSpecification("EARNINGS 3 CODE"));
		header.add(new ColumnSpecification("EARNINGS 3 AMOUNT"));
		header.add(new ColumnSpecification("EARNINGS 4 CODE"));
		header.add(new ColumnSpecification("EARNINGS 4 AMOUNT"));
		header.add(new ColumnSpecification("EARNINGS 5 CODE"));
		header.add(new ColumnSpecification("EARNINGS 5 AMOUNT"));
	}
	public Name10_07_16_DeltekDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
        super( tableType,lineend);
    }
}



