
package com.odysystems.soap.ultipro.employeePerson;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEmployeePerson", targetNamespace = "http://www.ultipro.com/services/employeeperson")
@XmlSeeAlso({ ObjectFactory.class })
@HandlerChain(file = "UltiproHandlerChain.xml	")
public interface IEmployeePerson {

	/**
	 * 
	 * @return returns com.odysystems.soap.ultipro.employeePerson.PingResponse
	 */
	@WebMethod(operationName = "Ping", action = "http://tempuri.org/IUesWcfService/Ping")
	@WebResult(name = "PingResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.employeePerson.Ping")
	@ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "com.odysystems.soap.ultipro.employeePerson.Joker")
	public PingResponse ping();

	/**
	 * 
	 * @param employeeIdentifier
	 * @return returns
	 *         com.odysystems.soap.ultipro.employeePerson.PersonGetResponse
	 */
	@WebMethod(operationName = "GetPersonByEmployeeIdentifier", action = "http://www.ultipro.com/services/employeeperson/IEmployeePerson/GetPersonByEmployeeIdentifier")
	@WebResult(name = "GetPersonByEmployeeIdentifierResult", targetNamespace = "http://www.ultipro.com/services/employeeperson")
	@RequestWrapper(localName = "GetPersonByEmployeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.GetPersonByEmployeeIdentifier")
	@ResponseWrapper(localName = "GetPersonByEmployeeIdentifierResponse", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.GetPersonByEmployeeIdentifierResponse")
	public PersonGetResponse getPersonByEmployeeIdentifier(
			@WebParam(name = "employeeIdentifier", targetNamespace = "http://www.ultipro.com/services/employeeperson") EmployeeIdentifier employeeIdentifier);

	/**
	 * 
	 * @param query
	 * @return returns
	 *         com.odysystems.soap.ultipro.employeePerson.PersonFindResponse
	 */
	//@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
	@WebMethod(operationName = "FindPeople", action = "http://www.ultipro.com/services/employeeperson/IEmployeePerson/FindPeople")
	@WebResult(name = "FindPeopleResult", targetNamespace = "http://www.ultipro.com/services/employeeperson")
	@RequestWrapper(localName = "FindPeople", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.FindPeople")
	@ResponseWrapper(localName = "FindPeopleResponse", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.FindPeopleResponse")
	public PersonFindResponse findPeople(
			@WebParam(name = "query", targetNamespace = "http://www.ultipro.com/services/employeeperson") EmployeeQuery query,
			@WebParam(name = "ClientAccessKey", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/clientaccesskey", header = true, partName = "ClientAccessKey") String clientAccessKey,
			@WebParam(name = "UltiProToken", targetNamespace = "http://www.ultimatesoftware.com/foundation/authentication/ultiprotoken", header = true, partName = "UltiProToken") String UltiProToken

	);

	/**
	 * 
	 * @param entities
	 * @return returns
	 *         com.odysystems.soap.ultipro.employeePerson.PersonUpdateResponse
	 */
	@WebMethod(operationName = "UpdatePerson", action = "http://www.ultipro.com/services/employeeperson/IEmployeePerson/UpdatePerson")
	@WebResult(name = "UpdatePersonResult", targetNamespace = "http://www.ultipro.com/services/employeeperson")
	@RequestWrapper(localName = "UpdatePerson", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.UpdatePerson")
	@ResponseWrapper(localName = "UpdatePersonResponse", targetNamespace = "http://www.ultipro.com/services/employeeperson", className = "com.odysystems.soap.ultipro.employeePerson.UpdatePersonResponse")
	public PersonUpdateResponse updatePerson(
			@WebParam(name = "entities", targetNamespace = "http://www.ultipro.com/services/employeeperson") ArrayOfPerson entities);

}
