
package com.odysystems.soap.ultipro.employeePerson;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Proxy_IEmployeePerson", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://service4.ultipro.com/services/EmployeePerson")
@HandlerChain(file = "UltiproHandlerChain.xml")
public class ProxyIEmployeePerson
    extends Service
{

    private final static URL PROXYIEMPLOYEEPERSON_WSDL_LOCATION;
    private final static WebServiceException PROXYIEMPLOYEEPERSON_EXCEPTION;
    private final static QName PROXYIEMPLOYEEPERSON_QNAME = new QName("http://tempuri.org/", "Proxy_IEmployeePerson");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service4.ultipro.com/services/EmployeePerson");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROXYIEMPLOYEEPERSON_WSDL_LOCATION = url;
        PROXYIEMPLOYEEPERSON_EXCEPTION = e;
    }

    public ProxyIEmployeePerson() {
        super(__getWsdlLocation(), PROXYIEMPLOYEEPERSON_QNAME);
    }

    public ProxyIEmployeePerson(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROXYIEMPLOYEEPERSON_QNAME, features);
    }

    public ProxyIEmployeePerson(URL wsdlLocation) {
        super(wsdlLocation, PROXYIEMPLOYEEPERSON_QNAME);
    }

    public ProxyIEmployeePerson(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROXYIEMPLOYEEPERSON_QNAME, features);
    }

    public ProxyIEmployeePerson(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProxyIEmployeePerson(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEmployeePerson
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeePerson")
    public IEmployeePerson getWSHttpBindingIEmployeePerson() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeePerson"), IEmployeePerson.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmployeePerson
     */
    @WebEndpoint(name = "WSHttpBinding_IEmployeePerson")
    public IEmployeePerson getWSHttpBindingIEmployeePerson(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IEmployeePerson"), IEmployeePerson.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROXYIEMPLOYEEPERSON_EXCEPTION!= null) {
            throw PROXYIEMPLOYEEPERSON_EXCEPTION;
        }
        return PROXYIEMPLOYEEPERSON_WSDL_LOCATION;
    }

}
